import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';

import { useEffect } from 'react';

import Header from '../components/header/header.component';
import Sidebar from '../components/sidebar/sidebar.component';

import styles from '../styles/Home.module.css';

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    router.push('/oformit-zakaz/page/1');
  })
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Главная</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar/>
    </div>
  )
}
