import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header/header.component'
import Sidebar from '../components/sidebar/sidebar.component'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Оформить заказ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar/>
    </div>
  )
}
